const countryArr = [
    {en:"Albania", ru:"Албания"},
    {en:"Andorra", ru:"Андорра"},
    {en:"Armenia", ru:"Армения"},
    {en:"Austria", ru:"Австрия"},
    {en:"Azerbaijan", ru:"Азербайджан"},
    {en:"Belarus", ru:"Белоруссия"},
    {en:"Belgium", ru:"Бельгия"},
    {en:"Bosnia and Herzegovina", ru:"Босния и Герцеговина"},
    {en:"Bulgaria", ru:"Болгария"},
    {en:"Croatia", ru:"Хорватия"},
    {en:"Cyprus", ru:"Северный Кипр"},
    {en:"Czech Republic", ru:"Чехия"},
    {en:"Denmark", ru:"Дания"},
    {en:"Estonia", ru:"Эстония"},
    {en:"Finland", ru:"Финляндия"},
    {en:"France", ru:"Франция"},
    {en:"Georgia", ru:"Грузия"},
    {en:"Germany", ru:"Германия"},
    {en:"Greece", ru:"Греция"},
    {en:"Hungary", ru:"Венгрия"},
    {en:"Iceland", ru:"Исландия"},
    {en:"Ireland", ru:"Ирландия"},
    {en:"Italy", ru:"Италия"},
    {en:"Kazakhstan", ru:"Казахстан"},
    {en:"Latvia", ru:"Латвия"},
    {en:"Liechtenstein", ru:"Лихтенштейн"},
    {en:"Lithuania", ru:"Литва"},
    {en:"Luxembourg", ru:"Люксембург"},
    {en:"Macedonia", ru:"Македония"},
    {en:"Malta", ru:"Мальта"},
    {en:"Moldova", ru:"Молдавия"},
    {en:"Monaco", ru:"Монако"},
    {en:"Netherlands", ru:"Нидерланды"},
    {en:"Norway", ru:"Норвегия"},
    {en:"Poland", ru:"Польша"},
    {en:"Portugal", ru:"Португалия"},
    {en:"Romania", ru:"Румыния"},
    {en:"Russia", ru:"Россия"},
    {en:"San_Marino", ru:"Сан-Марино"},
    {en:"Serbia", ru:"Сербия"},
    {en:"Slovakia", ru:"Словакия"},
    {en:"Slovenia", ru:"Словения"},
    {en:"Spain", ru:"Испания"},
    {en:"Sweden", ru:"Швеция"},
    {en:"Switzerland", ru:"Швейцария"},
    {en:"Turkey", ru:"Турция"},
    {en:"Ukraine", ru:"Украина"},
    {en:"United Kingdom", ru:"Великобритания"},
    {en:"Vatican City", ru:"Ватикан"}
];
export default countryArr;